docker cp logo.png open-webui:/app/backend/open_webui/static/logo.png
docker cp logo.png open-webui:/app/backend/open_webui/static/swagger-ui/favicon.png
docker cp logo.png open-webui:/app/backend/open_webui/static/splash.png
docker cp logo.png open-webui:/app/backend/open_webui/static/favicon.png
docker cp logo.png open-webui:/app/build/favicon/apple-touch-icon.png
docker cp logo.png open-webui:/app/build/favicon/web-app-manifest-512x512.png
docker cp logo.png open-webui:/app/build/favicon/favicon-96x96.png
docker cp logo.png open-webui:/app/build/favicon/web-app-manifest-192x192.png
docker cp logo.png open-webui:/app/build/static/splash-dark.png
docker cp logo.png open-webui:/app/build/static/splash.png
docker cp logo.png open-webui:/app/build/static/favicon.png
docker cp logo.png open-webui:/app/build/favicon.png
